.PHONY: clean

#Definition de variable
#Nom de l'executable
PJNAME = automate
#Variable pour ranger les fichiers objets etc..
SRCDIR = ./src/
OBJDIR = ./obj/
BINDIR = ./bin/

$(PJNAME): $(OBJDIR)argument.o $(OBJDIR)automaton.o $(OBJDIR)parcours.o $(OBJDIR)main.o
	gcc -o automate $(OBJDIR)argument.o $(OBJDIR)automaton.o $(OBJDIR)parcours.o $(OBJDIR)main.o

$(OBJDIR)automaton.o: $(SRCDIR)automaton.c $(SRCDIR)automaton.h $(SRCDIR)type.h
	gcc -c -o $(OBJDIR)automaton.o $(SRCDIR)automaton.c

$(OBJDIR)parcours.o: $(SRCDIR)parcours.c $(SRCDIR)parcours.h $(OBJDIR)automaton.o
	gcc -c -o $(OBJDIR)parcours.o $(SRCDIR)parcours.c

$(OBJDIR)argument.o: $(SRCDIR)argument.c $(SRCDIR)argument.h $(OBJDIR)parcours.o
	gcc -c -o $(OBJDIR)argument.o $(SRCDIR)argument.c

$(OBJDIR)main.o: $(OBJDIR)argument.o $(OBJDIR)automaton.o $(OBJDIR)parcours.o
	gcc -c -o $(OBJDIR)main.o $(SRCDIR)main.c

clean:
	rm -f $(OBJDIR)*.o
